### ISSUE TITLE
Dockutil - Encoding error ?

### ISSUE THREAD

**Issue by arsonik** [osxc/legacy-common#18]
Hi guys,

Any ideas, to solve that issue ?

```
TASK: [dock | add apps] *******************************************************
<localhost> REMOTE_MODULE command ~/src/github.com/kcrawford/dockutil/scripts/dockutil --add /Applications/Finder.app
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1399881877.09-60038311989509 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1399881877.09-60038311989509 && echo $HOME/.ansible/tmp/ansible-tmp-1399881877.09-60038311989509']
<localhost> PUT /var/folders/3x/ldtzdqpx2sz9bz64lsq1x8w40000gn/T/tmpkjR7xv TO /Users/florian/.ansible/tmp/ansible-tmp-1399881877.09-60038311989509/command
<localhost> EXEC ['/bin/sh', '-c', u'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /Users/florian/.ansible/tmp/ansible-tmp-1399881877.09-60038311989509/command; rm -rf /Users/florian/.ansible/tmp/ansible-tmp-1399881877.09-60038311989509/ >/dev/null 2>&1']
failed: [localhost] => (item=/Applications/Finder.app) => {"changed": true, "cmd": ["~/src/github.com/kcrawford/dockutil/scripts/dockutil", "--add", "/Applications/Finder.app"], "delta": "0:00:00.119017", "end": "2014-05-12 10:04:37.266834", "item": "/Applications/Finder.app", "rc": 1, "start": "2014-05-12 10:04:37.147817"}
stderr: Traceback (most recent call last):
  File "/Users/florian/src/github.com/kcrawford/dockutil/scripts/dockutil", line 627, in <module>
    main()
  File "/Users/florian/src/github.com/kcrawford/dockutil/scripts/dockutil", line 340, in main
    if addItem(pl, real_add_path, replace_label, position, before_item, after_item, section, displayas, showas, arrangement, tile_type, label_name):
  File "/Users/florian/src/github.com/kcrawford/dockutil/scripts/dockutil", line 485, in addItem
    add_path = unicode(add_path, sys.stdin.encoding)
TypeError: unicode() argument 2 must be string, not None
```

```
❯❯❯ python
Python 2.7.5 (default, Aug 25 2013, 00:04:04)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

```
❯❯❯ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

Tests

```
❯❯❯ cat ./test
#!/usr/bin/python
import sys
print sys.stdin.encoding
print unicode("test", sys.stdin.encoding)
```

```
❯❯❯ ./test
UTF-8
test
```

The script itself work as expected

```
❯❯❯ ~/src/github.com/kcrawford/dockutil/scripts/dockutil --add /Applications/Finder.app                                                                                                                                                                                               ⏎
```

Thank you !

**Comment by rricard** [comment]
Seems like the answer is in #17. See the followup there !

**Comment by arsonik** [comment]
sorry for the duplicate.
 :+1:  Thank you for the fix
